
# [CVE-2022-48560](https://bugs.python.org/issue39421)

## Description

- `A use-after-free exists in Python through 3.9 via heappushpop in heapq.`

## Cvss Data

- **Access Vector**:
  - 
- **Base Score**:
  - 

## Scores

- **Exploitability Score**:
  - 
- **Impact Score**:
  - 
- **Base Severity**:
  - 

## Other Information

- **Publish Date**:
  - 2023-08-22 19:16:31
- **Vulnerability Status**:
  - Modified

## References

- **cve@mitre.org**: https://bugs.python.org/issue39421
- **cve@mitre.org**: https://lists.debian.org/debian-lts-announce/2023/09/msg00022.html
- **cve@mitre.org**: https://lists.debian.org/debian-lts-announce/2023/10/msg00017.html
- **cve@mitre.org**: https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/JZ5OOBWNYWXFTZDMCGHJVGDLDTHLWITJ/
- **cve@mitre.org**: https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/VO7Y2YZSDK3UYJD2KBGLXRTGNG6T326J/
- **cve@mitre.org**: https://security.netapp.com/advisory/ntap-20230929-0008/
