
# [CVE-2009-5010](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2009-5010)

## Description

- `Race condition in the FTPHandler class in ftpserver.py in pyftpdlib before 0.5.1 allows remote attackers to cause a denial of service (daemon outage) by establishing and then immediately closing a TCP connection, leading to the accept function having an unexpected return value of None, a different vulnerability than CVE-2010-3494.`

## Cvss Data

- **Access Vector**:
  - NETWORK
- **Base Score**:
  - 4.3

## Scores

- **Exploitability Score**:
  - 8.6
- **Impact Score**:
  - 2.9
- **Base Severity**:
  - MEDIUM

## Other Information

- **Publish Date**:
  - 2010-10-19 20:00:02
- **Vulnerability Status**:
  - Analyzed

## References

- **cve@mitre.org**: http://bugs.python.org/issue6706
- **cve@mitre.org**: http://code.google.com/p/pyftpdlib/issues/detail?id=91
- **cve@mitre.org**: http://code.google.com/p/pyftpdlib/source/browse/trunk/HISTORY
- **cve@mitre.org**: http://code.google.com/p/pyftpdlib/source/detail?r=439
- **cve@mitre.org**: http://code.google.com/p/pyftpdlib/source/diff?spec=svn439&r=439&format=side&path=/trunk/pyftpdlib/ftpserver.py
- **cve@mitre.org**: http://www.openwall.com/lists/oss-security/2010/09/09/6
- **cve@mitre.org**: http://www.openwall.com/lists/oss-security/2010/09/11/2
- **cve@mitre.org**: http://www.openwall.com/lists/oss-security/2010/09/22/3
- **cve@mitre.org**: http://www.openwall.com/lists/oss-security/2010/09/24/3
- **cve@mitre.org**: https://bugs.launchpad.net/zodb/+bug/135108
