
# [CVE-2015-3206](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2015-3206)

## Description

- `The checkPassword function in python-kerberos does not authenticate the KDC it attempts to communicate with, which allows remote attackers to cause a denial of service (bad response), or have other unspecified impact by performing a man-in-the-middle attack.`

## Cvss Data

- **Access Vector**:
  - NETWORK
- **Base Score**:
  - 6.8

## Scores

- **Exploitability Score**:
  - 8.6
- **Impact Score**:
  - 6.4
- **Base Severity**:
  - MEDIUM

## Other Information

- **Publish Date**:
  - 2017-08-25 18:29:00
- **Vulnerability Status**:
  - Analyzed

## References

- **secalert@redhat.com**: http://www.openwall.com/lists/oss-security/2015/05/21/3
- **secalert@redhat.com**: http://www.securityfocus.com/bid/74760
- **secalert@redhat.com**: https://bugzilla.redhat.com/show_bug.cgi?id=1223802
- **secalert@redhat.com**: https://github.com/apple/ccs-pykerberos/issues/31
- **secalert@redhat.com**: https://pypi.python.org/pypi/kerberos
