
# [CVE-2012-2135](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2012-2135)

## Description

- `The utf-16 decoder in Python 3.1 through 3.3 does not update the aligned_end variable after calling the unicode_decode_call_errorhandler function, which allows remote attackers to obtain sensitive information (process memory) or cause a denial of service (memory corruption and crash) via unspecified vectors.`

## Cvss Data

- **Access Vector**:
  - NETWORK
- **Base Score**:
  - 6.4

## Scores

- **Exploitability Score**:
  - 10.0
- **Impact Score**:
  - 4.9
- **Base Severity**:
  - MEDIUM

## Other Information

- **Publish Date**:
  - 2012-08-14 22:55:01
- **Vulnerability Status**:
  - Analyzed

## References

- **secalert@redhat.com**: http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=670389
- **secalert@redhat.com**: http://bugs.python.org/issue14579
- **secalert@redhat.com**: http://secunia.com/advisories/51087
- **secalert@redhat.com**: http://secunia.com/advisories/51089
- **secalert@redhat.com**: http://www.openwall.com/lists/oss-security/2012/04/25/2
- **secalert@redhat.com**: http://www.openwall.com/lists/oss-security/2012/04/25/4
- **secalert@redhat.com**: http://www.ubuntu.com/usn/USN-1615-1
- **secalert@redhat.com**: http://www.ubuntu.com/usn/USN-1616-1
