
# [CVE-2020-35917](https://rustsec.org/advisories/RUSTSEC-2020-0074.html)

## Description

- `An issue was discovered in the pyo3 crate before 0.12.4 for Rust. There is a reference-counting error and use-after-free in From<Py<T>>.`

## Cvss Data

- **Access Vector**:
  - LOCAL
- **Base Score**:
  - 2.1

## Scores

- **Exploitability Score**:
  - 3.9
- **Impact Score**:
  - 2.9
- **Base Severity**:
  - LOW

## Other Information

- **Publish Date**:
  - 2020-12-31 09:15:15
- **Vulnerability Status**:
  - Analyzed

## References

- **cve@mitre.org**: https://rustsec.org/advisories/RUSTSEC-2020-0074.html
